kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-controller-binding
  namespace: ingress-basic
subjects:
- kind: ServiceAccount
  name: ingress-controller
  namespace: ingress-basic
roleRef:
  kind: ClusterRole
  name: ingress-controller
  apiGroup: rbac.authorization.k8s.io
