apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ingress-basic
  labels:
    app: product
spec:
  selector:
    app: product
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
